# -*- coding: utf-8 -*-
"""CodeAlpha Task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifi-0m2B4vFQlDi-2bHaOzhpLK3RVzmS

**Smart** FAQ Chatbot


This is made with new Way using Gradio Library!
"""

!pip install -q gradio sentence-transformers scikit-learn pandas

import gradio as gr
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Load Model (Sirf ek dafa load hoga)
print("Loading AI Model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

# 2. Knowledge Base (FAQs)
faq_data = [
    {"question": "How can I track my order?", "answer": "You can easily track your order by clicking the 'Track Order' link in your shipping confirmation email."},
    {"question": "What is your return policy?", "answer": "We offer a 30-day return policy. Items must be unworn and in their original packaging."},
    {"question": "Do you offer international shipping?", "answer": "Yes, we ship worldwide! Shipping costs and delivery times vary by country."},
    {"question": "How long does shipping take?", "answer": "Standard shipping usually takes 3-5 business days, while express shipping takes 1-2 business days."},
    {"question": "Can I change my order after placing it?", "answer": "Orders can only be modified within 1 hour of placement. Please contact support immediately."},
    {"question": "What payment methods do you accept?", "answer": "We accept Visa, MasterCard, PayPal, and Apple Pay."}
]
df = pd.DataFrame(faq_data)

# 3. Text ko Vectors (Numbers) mein convert karna
faq_embeddings = model.encode(df['question'].tolist())

# 4. Chatbot ka Dimagh (Logic)
def respond(message, history):
    # User ke sawal ko vector banayen
    query_vector = model.encode([message])

    # FAQs ke sath similarity check karein
    similarities = cosine_similarity(query_vector, faq_embeddings)[0]

    # Sab se behtareen match dhoondein
    best_match_index = np.argmax(similarities)
    best_score = similarities[best_match_index]

    # Agar match 50% se zyada acha hai toh jawab dein
    if best_score > 0.5:
        return df.iloc[best_match_index]['answer']
    else:
        return "I'm sorry, I don't have an exact answer for that in my FAQs. Please try rephrasing your question."

# 5. Gradio ka VIP Chat Interface
demo = gr.ChatInterface(
    respond,
    title="🤖 Smart FAQ Assistant",
    description="Ask me anything about our services, shipping, or returns!",
    theme="soft",
    examples=["How can I track my order?", "Do you offer international shipping?", "What payment methods do you accept?"]
)

# 6. App ko Live karna (Share=True ki wajah se public link banega)
demo.launch(share=True)