# -*- coding: utf-8 -*-
"""CodeAlpha Task4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CFls_WeG2FBkpCFlTlmKT3vWKUildBp
"""

!pip install -q gradio ultralytics opencv-python-headless

import gradio as gr
from ultralytics import YOLO
import cv2
import numpy as np

print("Loading YOLOv8 AI Model... (Takes a few seconds the first time)")
# YOLOv8 nano model (fastest and perfect for Colab)
model = YOLO('yolov8n.pt')

def detect_objects(image):
    if image is None:
        return None

    # 1. AI ko image dena inference (detection) ke liye
    results = model(image)

    # 2. Results ko image par draw karna (Bounding boxes aur Labels)
    res_image = results[0].plot()

    # 3. OpenCV colors (BGR) ko Gradio colors (RGB) mein convert karna
    final_image = cv2.cvtColor(res_image, cv2.COLOR_BGR2RGB)

    return final_image

# --- Gradio VIP Interface ---
with gr.Blocks(theme=gr.themes.Monochrome()) as demo:
    gr.Markdown("<h1 style='text-align: center;'>👁️ Real-Time Object Detection AI</h1>")
    gr.Markdown("<p style='text-align: center;'>Upload an image or take a picture using your webcam to detect objects instantly using YOLOv8!</p>")

    with gr.Row():
        # Input Section: Webcam aur File Upload dono options maujood hain
        input_img = gr.Image(sources=["webcam", "upload"], type="numpy", label="Input Image / Webcam")

        # Output Section: Bounding boxes wali image
        output_img = gr.Image(type="numpy", label="AI Detections", interactive=False)

    with gr.Row():
        detect_btn = gr.Button("Scan & Detect Objects ✨", variant="primary")
        clear_btn = gr.ClearButton(components=[input_img, output_img], value="Clear")

    # Button click event
    detect_btn.click(fn=detect_objects, inputs=input_img, outputs=output_img)

# App ko Live karna
demo.launch(share=True)